version: '3.1'

services:
  db:
    image: 'mysql:latest'
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_DATABASE: 'todolist'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
